[build]
  command = "npx prisma generate && npx prisma db push && npm run build"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  included_files = ["node_modules/@prisma/client/**", "node_modules/@prisma/adapter-libsql/**", "node_modules/@libsql/**"]
