CREATE TABLE IF NOT EXISTS "MaternalPatient" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "admissionNumber" TEXT NOT NULL,
    "bedNumber" TEXT,
    "lastName" TEXT NOT NULL,
    "firstName" TEXT NOT NULL,
    "middleName" TEXT,
    "age" INTEGER NOT NULL,
    "gender" TEXT NOT NULL DEFAULT 'Female',
    "civilStatus" TEXT NOT NULL DEFAULT 'Single',
    "address" TEXT NOT NULL,
    "religion" TEXT,
    "dateOfBirth" DATETIME NOT NULL,
    "placeOfBirth" TEXT,
    "nationality" TEXT NOT NULL DEFAULT 'Filipino',
    "occupation" TEXT,
    "philhealthNumber" TEXT,
    "philhealthStatus" TEXT,
    "husbandName" TEXT,
    "contactNumber" TEXT NOT NULL,
    "companionName" TEXT,
    "companionRelation" TEXT,
    "dateAdmitted" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "timeAdmitted" TEXT,
    "admittedBy" TEXT,
    "dateDischarged" DATETIME,
    "timeDischarged" TEXT,
    "dischargedBy" TEXT,
    "attendingPhysician" TEXT,
    "admittingDiagnosis" TEXT,
    "finalDiagnosis" TEXT,
    "gravida" INTEGER NOT NULL DEFAULT 0,
    "term" INTEGER NOT NULL DEFAULT 0,
    "preterm" INTEGER NOT NULL DEFAULT 0,
    "abortion" INTEGER NOT NULL DEFAULT 0,
    "living" INTEGER NOT NULL DEFAULT 0,
    "lmp" DATETIME,
    "edc" DATETIME,
    "aog" TEXT,
    "bow" TEXT,
    "pallor" TEXT,
    "edema" TEXT,
    "fundalHeight" TEXT,
    "fetalHeartTone" TEXT,
    "internalExam" TEXT,
    "status" TEXT NOT NULL DEFAULT 'Active',
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL
);
CREATE TABLE IF NOT EXISTS "NewbornRecord" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "maternalPatientId" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "gender" TEXT NOT NULL,
    "dateOfBirth" DATETIME NOT NULL,
    "timeOfBirth" TEXT,
    "dateAdmitted" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "timeAdmitted" TEXT,
    "icdCode" TEXT,
    "admissionDiagnosis" TEXT,
    "finalDiagnosis" TEXT,
    "mannerOfDelivery" TEXT NOT NULL DEFAULT 'NSD',
    "headCircumference" REAL,
    "chestCircumference" REAL,
    "abdominalCircumference" REAL,
    "length" REAL,
    "weight" REAL,
    "status" TEXT NOT NULL DEFAULT 'Active',
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL,
    CONSTRAINT "NewbornRecord_maternalPatientId_fkey" FOREIGN KEY ("maternalPatientId") REFERENCES "MaternalPatient" ("id") ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE TABLE IF NOT EXISTS "VitalSign" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "date" TEXT NOT NULL,
    "time" TEXT NOT NULL,
    "bloodPressure" TEXT,
    "pulseRate" TEXT,
    "respiratoryRate" TEXT,
    "temperature" TEXT,
    "signature" TEXT,
    "maternalPatientId" TEXT,
    "newbornRecordId" TEXT,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "VitalSign_maternalPatientId_fkey" FOREIGN KEY ("maternalPatientId") REFERENCES "MaternalPatient" ("id") ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT "VitalSign_newbornRecordId_fkey" FOREIGN KEY ("newbornRecordId") REFERENCES "NewbornRecord" ("id") ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE TABLE IF NOT EXISTS "Medication" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "medicationName" TEXT NOT NULL,
    "dateGiven" TEXT NOT NULL,
    "timeGiven" TEXT,
    "route" TEXT NOT NULL DEFAULT 'IM',
    "givenBy" TEXT,
    "maternalPatientId" TEXT,
    "newbornRecordId" TEXT,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "Medication_maternalPatientId_fkey" FOREIGN KEY ("maternalPatientId") REFERENCES "MaternalPatient" ("id") ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT "Medication_newbornRecordId_fkey" FOREIGN KEY ("newbornRecordId") REFERENCES "NewbornRecord" ("id") ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE TABLE IF NOT EXISTS "NurseNote" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "date" TEXT NOT NULL,
    "time" TEXT,
    "shift" TEXT,
    "focus" TEXT,
    "data" TEXT,
    "action" TEXT,
    "response" TEXT,
    "maternalPatientId" TEXT,
    "newbornRecordId" TEXT,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "NurseNote_maternalPatientId_fkey" FOREIGN KEY ("maternalPatientId") REFERENCES "MaternalPatient" ("id") ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT "NurseNote_newbornRecordId_fkey" FOREIGN KEY ("newbornRecordId") REFERENCES "NewbornRecord" ("id") ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE TABLE IF NOT EXISTS "OutputChart" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "date" TEXT NOT NULL,
    "shift" TEXT NOT NULL DEFAULT 'AM',
    "stoolCount" INTEGER NOT NULL DEFAULT 0,
    "urineCount" INTEGER NOT NULL DEFAULT 0,
    "maternalPatientId" TEXT,
    "newbornRecordId" TEXT,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "OutputChart_maternalPatientId_fkey" FOREIGN KEY ("maternalPatientId") REFERENCES "MaternalPatient" ("id") ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT "OutputChart_newbornRecordId_fkey" FOREIGN KEY ("newbornRecordId") REFERENCES "NewbornRecord" ("id") ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE TABLE IF NOT EXISTS "LabResult" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "maternalPatientId" TEXT NOT NULL,
    "datePerformed" TEXT,
    "wbcCount" TEXT,
    "rbcCount" TEXT,
    "hemoglobin" TEXT,
    "hematocrit" TEXT,
    "mcv" TEXT,
    "mch" TEXT,
    "mchc" TEXT,
    "neutrophils" TEXT,
    "lymphocytes" TEXT,
    "monocytes" TEXT,
    "eosinophils" TEXT,
    "basophils" TEXT,
    "plateletCount" TEXT,
    "urineColor" TEXT,
    "urineTransparency" TEXT,
    "urineReaction" TEXT,
    "urinePH" TEXT,
    "urineSpecificGravity" TEXT,
    "urineGlucose" TEXT,
    "urineProtein" TEXT,
    "urineWBC" TEXT,
    "urineRBC" TEXT,
    "urineEpithelialCells" TEXT,
    "urineMicroscopicOther" TEXT,
    "bloodTypeABO" TEXT,
    "bloodTypeRh" TEXT,
    "antiA" TEXT,
    "antiB" TEXT,
    "antiD" TEXT,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "LabResult_maternalPatientId_fkey" FOREIGN KEY ("maternalPatientId") REFERENCES "MaternalPatient" ("id") ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE TABLE IF NOT EXISTS "UltrasoundResult" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "maternalPatientId" TEXT NOT NULL,
    "datePerformed" TEXT,
    "impression" TEXT,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "UltrasoundResult_maternalPatientId_fkey" FOREIGN KEY ("maternalPatientId") REFERENCES "MaternalPatient" ("id") ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE TABLE IF NOT EXISTS "PostpartumRecord" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "maternalPatientId" TEXT NOT NULL,
    "assessmentTime" TEXT NOT NULL,
    "bleeding" TEXT,
    "uterusFirmness" TEXT,
    "bloodPressure" TEXT,
    "pulse" TEXT,
    "urineVoided" TEXT,
    "vulvaStatus" TEXT,
    "newbornBreathing" TEXT,
    "newbornWarmth" TEXT,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "PostpartumRecord_maternalPatientId_fkey" FOREIGN KEY ("maternalPatientId") REFERENCES "MaternalPatient" ("id") ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE TABLE IF NOT EXISTS "ApgarScore" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "newbornRecordId" TEXT NOT NULL,
    "minuteType" TEXT NOT NULL DEFAULT '1min',
    "heartRate" INTEGER NOT NULL DEFAULT 0,
    "respiratoryEffort" INTEGER NOT NULL DEFAULT 0,
    "muscleTone" INTEGER NOT NULL DEFAULT 0,
    "reflexIrritability" INTEGER NOT NULL DEFAULT 0,
    "skinColor" INTEGER NOT NULL DEFAULT 0,
    "totalScore" INTEGER NOT NULL DEFAULT 0,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "ApgarScore_newbornRecordId_fkey" FOREIGN KEY ("newbornRecordId") REFERENCES "NewbornRecord" ("id") ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE UNIQUE INDEX "MaternalPatient_admissionNumber_key" ON "MaternalPatient"("admissionNumber");
